export const PROFILE_IMAGE = "/mignon.jpeg";

export const PROJECTS = [
  {
    id: 1,
    title: "Maverik Social Media Campaign",
    context: "Internship",
    category: "Social Media",
    company: "Maverik",
    date: "2023-12-01",
    thumbnail: "/portfolio/maverik-thumb.png",
    description: "Created and curated 10+ social media posts and captions weekly for Maverik's Instagram, drawing on current consumer trends and the brand's adventure-first identity. Facilitated the launch of 2 marketing campaigns with high-profile sponsors including Red Bull and Ferrara.",
    goal: "Boost Instagram engagement and build authentic brand affinity among Maverik's Gen Z audience through trend-driven, relatable content that reflected the adventurous lifestyle the brand stands for.",
    results: "Boosted Instagram engagement 100x — from an average of 600 views per post to up to 60,000. Successfully launched 2 sponsored campaigns, coordinating creative assets and timelines with Red Bull and Ferrara.",
    gallery: [
      "/portfolio/maverik-thumb.png",
      "/portfolio/maverik-1.png",
      "/portfolio/maverik-2.png",
      "/portfolio/maverik-3.png",
      "/portfolio/maverik-4.png",
      "/portfolio/maverik-5.png",
      "/portfolio/maverik-6.png",
      "/portfolio/maverik-7.png",
      "/portfolio/maverik-8.png",
      "/portfolio/maverik-9.png",
      "/portfolio/maverik-10.png",
    ],
  },
  {
    id: 2,
    title: "Circle K Power BI Dashboards",
    context: "Job",
    category: "Data Analytics",
    company: "Circle K",
    date: "2025-06-01",
    thumbnail: "https://media.base44.com/images/public/69c89613f2f68664d2b3affc/be101a47e_generated_b0968a9e.png",
    description: "Built and launched 10+ Power BI reports to surface promotion insights, sales trends, and stakeholder KPIs across Circle K's corporate and franchise network. Identified $2M in sales misattribution by refining backend logic to properly separate Corporate vs. Franchise reporting.",
    goal: "Give regional and corporate stakeholders clear, reliable dashboards to make data-driven decisions — and fix long-standing data quality issues that were obscuring the true sales picture.",
    results: "Delivered 10+ live Power BI reports used by stakeholders across the business. Reclassified $2M in misattributed sales. Added CAD/USD currency conversion enabling international stakeholder access. Produced 10 training videos to streamline analyst onboarding.",
    gallery: [
      "https://media.base44.com/images/public/69c89613f2f68664d2b3affc/be101a47e_generated_b0968a9e.png",
    ],
  },
  {
    id: 3,
    title: "Event & Invitation Design",
    context: "Personal",
    category: "Print & Digital",
    company: "Freelance",
    date: "2024-06-01",
    thumbnail: "/portfolio/invite-thumb.png",
    description: "Designed custom event stationery and invitation suites for private clients — from baby showers to wedding receptions. Each piece combined botanical illustration, elegant typography, and cohesive color systems to create a polished, personal feel.",
    goal: "Give clients beautifully crafted invitations that feel personal and print-ready, without the corporate template look — every design tailored to the event's tone and the client's personality.",
    results: "Completed multiple custom invitation suites with 100% client satisfaction. Repeat clients and referral-based commissions. Designs spanned baby showers, wedding ceremonies, and reception events.",
    gallery: [
      "/portfolio/invite-thumb.png",
      "/portfolio/invite-2.png",
      "/portfolio/invite-3.png",
      "/portfolio/invite-4.png",
    ],
  },
  {
    id: 4,
    title: "SOZA Brand & Landing Page",
    context: "Personal",
    category: "General Marketing",
    company: "Freelance",
    date: "2024-03-01",
    thumbnail: "/portfolio/soza-thumb.png",
    description: "Designed the brand identity and digital landing page for SOZA, a sparkling beverage brand. The design system used a dark, sophisticated palette to position the product as a premium, everyday indulgence — 'Happy Hour, Every Hour.'",
    goal: "Create a brand presence that feels modern and elevated, turning a simple sparkling drink into a lifestyle product with a strong visual identity and a compelling digital storefront.",
    results: "Delivered a complete brand and landing page design including color system, typography, product photography layout, and CTA flow — ready for web development handoff.",
    gallery: [
      "/portfolio/soza-thumb.png",
    ],
  },
  {
    id: 5,
    title: "H2GO Brand Identity",
    context: "Personal",
    category: "Print & Digital",
    company: "Freelance",
    date: "2023-09-01",
    thumbnail: "/portfolio/h2go-thumb.jpg",
    description: "Designed the logo and brand identity for H2GO, a hydration brand. The mark integrates a water droplet into clean, bold lettering — keeping it simple, memorable, and versatile across digital and print applications.",
    goal: "Build a logo that clearly communicates the brand's purpose — clean, refreshing hydration — while being strong enough to stand alone across packaging, apparel, and digital channels.",
    results: "Delivered a final logo mark and brand identity system. Clean, scalable design suited for both physical product packaging and digital marketing use.",
    gallery: [
      "/portfolio/h2go-thumb.jpg",
    ],
  },
  {
    id: 6,
    title: "BYU Marketing Collateral",
    context: "Job",
    category: "General Marketing",
    company: "BYU Marketing Advisory Center",
    date: "2024-04-01",
    thumbnail: "/portfolio/byu-thumb.png",
    description: "Created event promotion graphics and educational collateral for the BYU Marketing Advisory Center, supporting student engagement, networking events, and career placement initiatives for 350+ marketing students.",
    goal: "Design professional, on-brand materials that communicate event details clearly and motivate student participation — from advisory board meetings to career info sessions.",
    results: "Produced event graphics used across digital channels and physical signage. Materials supported successful student networking events and contributed to career placement outcomes for hundreds of marketing students.",
    gallery: [
      "/portfolio/byu-thumb.png",
      "/portfolio/byu-2.png",
    ],
  },
];

export const EXPERIENCES = [
  {
    id: 1,
    role: "Implementation Specialist",
    company: "Alleva",
    period: "July 2025 – Present",
    description: "Onboard a new client each week onto customized behavioral health software, consulting on workflows and configuring systems to match each facility's needs. Recognized by a client for leading the \"best tech implementation they've ever seen\". Build comprehensive facility reports using Looker to enable data-driven decision-making.",
    filterCompany: "Alleva",
  },
  {
    id: 2,
    role: "Placement & Teaching Assistant",
    company: "BYU Marketing Advisory Center",
    period: "Jan 2024 – Apr 2025",
    description: "Taught 20+ university lectures covering career planning and strategy. Collaborated on 14 weeks of educational content including videos, presentations, and worksheets. Facilitated career placement for 350+ marketing students through strategic guidance and industry connections.",
    filterCompany: "BYU Marketing Advisory Center",
  },
  {
    id: 3,
    role: "Research Assistant",
    company: "BYU Marketing & Global Supply Chain",
    period: "Jan 2024 – Apr 2025",
    description: "Collaborated with Expert Voice to research online consumer trust (publication pending). Conducted literature analysis and developed a conjoint study on Qualtrics to gather consumer insights on online expertise.",
    filterCompany: "BYU Marketing Advisory Center",
  },
  {
    id: 4,
    role: "Business Analytics Intern",
    company: "Circle K",
    period: "May 2024 – Jun 2025",
    description: "Built 10+ Power BI reports supporting stakeholder needs and promotion insights. Identified $2M in sales misattribution by refining backend logic for Corporate vs. Franchise reporting. Created Power BI training videos to streamline onboarding and added currency conversion for CAD/USD stakeholder access.",
    filterCompany: "Circle K",
  },
  {
    id: 5,
    role: "Marketing & Social Media Intern",
    company: "Maverik",
    period: "Aug – Dec 2023",
    description: "Facilitated the launch of 2 marketing campaigns with sponsors including Red Bull and Ferrara. Boosted Instagram engagement 100x — from an average of 600 views to up to 60,000. Curated 10+ social posts and captions weekly inspired by current consumer trends.",
    filterCompany: "Maverik",
  },
  {
    id: 6,
    role: "Strategic Planning Team Lead",
    company: "Gabb Wireless",
    period: "Jan – Apr 2023",
    description: "Led a team of 5 in preparing and presenting research findings to company stakeholders. Generated a creative launch campaign for a kids' music streaming service and prepared influencer marketing strategies to reach 50,000+ individuals.",
    filterCompany: "Gabb",
  },
];

export const CATEGORIES = ["Social Media", "Data Analytics", "General Marketing", "Print & Digital"];
export const CONTEXTS = ["Job", "Internship", "Personal"];