export const PROFILE_IMAGE = "/mignon.jpeg";

export const PROJECTS = [
  {
    id: 1,
    title: "Maverik Social Media Campaign",
    context: "Job",
    category: "Social Media",
    company: "Maverik",
    date: "2023-11-01",
    thumbnail: "/portfolio/maverik-cover.jpg",
    description: "Created and curated 10+ social media posts and captions weekly for Maverik's Instagram, drawing on current consumer trends and the brand's adventure-first identity. Facilitated the launch of 2 marketing campaigns with high-profile sponsors including Red Bull and Ferrara.",
    goal: "Boost Instagram engagement and build authentic brand affinity among Maverik's Gen Z audience through trend-driven, relatable content that reflected the adventurous lifestyle the brand stands for.",
    results: "Boosted Instagram engagement 100x — from an average of 600 views per post to up to 60,000. Successfully launched 2 sponsored campaigns, coordinating creative assets and timelines with Red Bull and Ferrara.",
    gallery: [
      "/portfolio/maverik-cover.jpg",
      "/portfolio/maverik-post-4.png",
      "/portfolio/maverik-post-6.png",
      "/portfolio/maverik-girl-math.png",
      "/portfolio/maverik-love-language.png",
    ],
  },
  {
    id: 3,
    title: "SOZA Brand Identity & Landing Page",
    context: "School",
    category: "Branding Projects",
    company: "Class Project",
    date: "2024-03-01",
    thumbnail: "/portfolio/soza-thumb.png",
    description: "Designed the full brand identity and digital landing page for SOZA, a sparkling beverage brand. The design system used a dark, sophisticated palette to position the product as a premium, everyday indulgence — 'Happy Hour, Every Hour.'",
    goal: "Create a brand presence that feels modern and elevated, turning a simple sparkling drink into a lifestyle product with a strong visual identity and a compelling digital storefront.",
    results: "Delivered a complete brand identity and landing page design including color system, typography, product photography layout, and CTA flow — ready for web development handoff.",
    gallery: [
      "/portfolio/soza-thumb.png",
      "/portfolio/soza-landing.png",
    ],
  },
  {
    id: 4,
    title: "H2GO Brand Identity",
    context: "School",
    category: "Branding Projects",
    company: "Class Project",
    date: "2023-09-01",
    thumbnail: "/portfolio/h2go-logo.jpg",
    description: "Designed the logo and brand identity for H2GO, a hydration brand. The mark integrates a water droplet into clean, bold lettering — keeping it simple, memorable, and versatile across digital and print applications. Included a video ad concept to bring the brand to life.",
    goal: "Build a logo that clearly communicates the brand's purpose — clean, refreshing hydration — while being strong enough to stand alone across packaging, apparel, and digital channels.",
    results: "Delivered a final logo mark, brand identity system, and a video ad concept. Clean, scalable design suited for both physical product packaging and digital marketing use.",
    gallery: [
      "/portfolio/h2go-logo.jpg",
      "/portfolio/h2go-video.mp4",
    ],
  },
  {
    id: 5,
    title: "Gerber Market Research",
    context: "School",
    category: "Branding Projects",
    company: "Class Project",
    date: "2023-06-01",
    thumbnail: "/portfolio/baby-food-thumb.png",
    description: "Conducted comprehensive market research for Gerber, analyzing consumer behavior, competitive landscape, and brand positioning opportunities in the premium baby food segment.",
    goal: "Identify unmet consumer needs and white-space positioning opportunities to inform a differentiated brand strategy.",
    results: "Produced a thorough market research report covering consumer insights, competitive analysis, and strategic brand recommendations.",
    gallery: [
      "/portfolio/baby-food-thumb.png",
    ],
  },
  {
    id: 6,
    title: "BoomCloud Brand Strategy",
    context: "School",
    category: "Branding Projects",
    company: "Class Project",
    date: "2023-03-01",
    thumbnail: "/portfolio/boomcloud-thumb.png",
    description: "Developed a full brand strategy and visual identity presentation for BoomCloud, a music/audio tech brand concept. Covered brand positioning, target audience, visual language, and go-to-market messaging.",
    goal: "Create a cohesive brand strategy that would differentiate BoomCloud in a crowded audio-tech market and resonate with a young, music-first consumer.",
    results: "Delivered a comprehensive brand strategy presentation covering positioning, visual identity, audience personas, and marketing approach.",
    gallery: [
      "/portfolio/boomcloud-thumb.png",
    ],
  },
  {
    id: 7,
    title: "Marketing Association Events",
    context: "School",
    category: "Print & Digital",
    company: "BYU Marketing Advisory Center",
    date: "2024-02-22",
    thumbnail: "/portfolio/mktg-assoc-1.png",
    description: "Created event promotion graphics and educational collateral for the BYU Marketing Advisory Center, supporting student engagement, networking events, and career placement initiatives for 350+ marketing students.",
    goal: "Design professional, on-brand materials that communicate event details clearly and motivate student participation — from advisory board meetings to career info sessions.",
    results: "Produced event graphics used across digital channels and physical signage. Materials supported successful student networking events and contributed to career placement outcomes for hundreds of marketing students.",
    gallery: [
      "/portfolio/mktg-assoc-1.png",
    ],
  },
  {
    id: 8,
    title: "Mignon Grad Announcements",
    context: "School",
    category: "Print & Digital",
    company: "Personal",
    date: "2024-05-01",
    thumbnail: "/portfolio/mignon-grad-1.png",
    description: "Designed custom graduation announcement graphics celebrating a personal milestone — combining clean typography, soft color palettes, and a celebratory aesthetic to mark the occasion.",
    goal: "Create polished, print-ready graduation announcement designs that feel personal and memorable.",
    results: "Delivered a custom announcement suite ready for digital sharing and print.",
    gallery: [
      "/portfolio/mignon-grad-1.png",
      "/portfolio/mignon-grad-2.png",
    ],
  },
  {
    id: 9,
    title: "Alyson and Benji Wedding Invites",
    context: "Personal",
    category: "Print & Digital",
    company: "Freelance",
    date: "2025-09-20",
    thumbnail: "/portfolio/aly-benji-couple.png",
    description: "Designed a complete wedding invitation suite for Alyson Ritz and Benjamin Garcia — including ceremony invitations, reception cards, and a 'night before' event invite. Each piece featured coordinated typography, elegant layout, and a cohesive aesthetic.",
    goal: "Give the couple beautifully crafted, print-ready invitation stationery that felt personal and elevated — not templated.",
    results: "Delivered a full three-piece wedding stationery suite with ceremony invite, reception card, and evening event invite — all print-ready.",
    gallery: [
      "/portfolio/aly-benji-couple.png",
      "/portfolio/aly-benji-reception-p-1.png",
      "/portfolio/aly-benji-ceremony-p-1.png",
      "/portfolio/aly-benji-nightbefore-p-1.png",
    ],
  },
  {
    id: 10,
    title: "Amy + Trey Wedding Invitations",
    context: "Personal",
    category: "Print & Digital",
    company: "Freelance",
    date: "2026-07-18",
    thumbnail: "/portfolio/amy-trey-2.png",
    description: "Designed wedding invitation and save-the-date graphics for Amy Ritz and Trey Richards — July 18, 2026 at Hatch Family Farm, Taylor, AZ. Clean, western-inspired design layered over an engagement photo backdrop.",
    goal: "Create on-brand, print-ready wedding stationery that captured the couple's personality and set the tone for their big day.",
    results: "Delivered a wedding invite and save-the-date suite ready for print and digital send.",
    gallery: [
      "/portfolio/amy-trey-2.png",
      "/portfolio/amy-trey-invite.png",
    ],
  },
  {
    id: 11,
    title: "Mary's Baby Shower Designs",
    context: "Personal",
    category: "Print & Digital",
    company: "Freelance",
    date: "2025-04-21",
    thumbnail: "/portfolio/mary-shower-1.png",
    description: "Designed custom baby shower graphics for Mary — soft, celebratory designs featuring botanical illustration and elegant typography to create a cohesive party aesthetic across digital and print materials.",
    goal: "Create a warm, coordinated graphic suite for the baby shower that felt special and personalized for Mary.",
    results: "Delivered a set of baby shower graphics ready for digital invitations, party signage, and print use.",
    gallery: [
      "/portfolio/mary-shower-1.png",
      "/portfolio/mary-shower-2.png",
      "/portfolio/mary-shower-3.png",
    ],
  },
  {
    id: 12,
    title: "Alyson's Graduation Photos",
    context: "Personal",
    category: "Print & Digital",
    company: "Freelance",
    date: "2023-12-01",
    thumbnail: "/portfolio/alyson-grad-1.png",
    description: "Designed and styled graduation photo announcement graphics for Alyson — combining her photos with custom typography treatments and layout designs for a polished, shareable result.",
    goal: "Create beautiful, shareable graduation graphic designs that highlight Alyson's photos in a polished, celebratory format.",
    results: "Delivered a full set of custom graduation graphics ready for digital sharing and print.",
    gallery: [
      "/portfolio/alyson-grad-1.png",
      "/portfolio/alyson-grad-2.png",
      "/portfolio/alyson-grad-3.png",
      "/portfolio/alyson-grad-4.png",
      "/portfolio/alyson-grad-5.png",
      "/portfolio/alyson-grad-6.png",
    ],
  },
];

export const EXPERIENCES = [
  {
    id: 1,
    role: "Implementation Specialist",
    company: "Alleva",
    period: "July 2025 – Present",
    description: "Onboard a new client each week onto customized behavioral health software, consulting on workflows and configuring systems to match each facility's needs. Recognized by a client for leading the \"best tech implementation they've ever seen\". Build comprehensive facility reports using Looker to enable data-driven decision-making.",
    filterCompany: "Alleva",
  },
  {
    id: 2,
    role: "Placement & Teaching Assistant",
    company: "BYU Marketing Advisory Center",
    period: "Jan 2024 – Apr 2025",
    description: "Taught 20+ university lectures covering career planning and strategy. Collaborated on 14 weeks of educational content including videos, presentations, and worksheets. Facilitated career placement for 350+ marketing students through strategic guidance and industry connections.",
    filterCompany: "BYU Marketing Advisory Center",
  },
  {
    id: 3,
    role: "Research Assistant",
    company: "BYU Marketing & Global Supply Chain",
    period: "Jan 2024 – Apr 2025",
    description: "Collaborated with Expert Voice to research online consumer trust (publication pending). Conducted literature analysis and developed a conjoint study on Qualtrics to gather consumer insights on online expertise.",
    filterCompany: "BYU Marketing Advisory Center",
  },
  {
    id: 4,
    role: "Business Analytics Intern",
    company: "Circle K",
    period: "May 2024 – Jun 2025",
    description: "Built 10+ Power BI reports supporting stakeholder needs and promotion insights. Identified $2M in sales misattribution by refining backend logic for Corporate vs. Franchise reporting. Created Power BI training videos to streamline onboarding and added currency conversion for CAD/USD stakeholder access.",
    filterCompany: "Circle K",
  },
  {
    id: 5,
    role: "Marketing & Social Media Intern",
    company: "Maverik",
    period: "Aug – Dec 2023",
    description: "Facilitated the launch of 2 marketing campaigns with sponsors including Red Bull and Ferrara. Boosted Instagram engagement 100x — from an average of 600 views to up to 60,000. Curated 10+ social posts and captions weekly inspired by current consumer trends.",
    filterCompany: "Maverik",
  },
  {
    id: 6,
    role: "Strategic Planning Team Lead",
    company: "Gabb Wireless",
    period: "Jan – Apr 2023",
    description: "Led a team of 5 in preparing and presenting research findings to company stakeholders. Generated a creative launch campaign for a kids' music streaming service and prepared influencer marketing strategies to reach 50,000+ individuals.",
    filterCompany: "Gabb",
  },
];

export const CATEGORIES = ["Social Media", "Branding Projects", "Print & Digital"];
export const CONTEXTS = ["Job", "School", "Personal"];
