export const PROFILE_IMAGE = "/mignon.jpeg";

export const PROJECTS = [
  {
    id: 9,
    title: "Alyson and Benji Wedding Invites",
    context: "Personal",
    category: "Print & Digital",
    company: "Freelance",
    date: "2025-09-20",
    thumbnail: "/portfolio/aly-benji-couple.png",
    description: "Made the full invite suite for Aly and Benji's wedding — ceremony card, reception card, and a night-before invite. Kept the look clean and cohesive across all three with their engagement photo woven in.",
    gallery: [
      "/portfolio/aly-benji-couple.png",
      "/portfolio/aly-benji-reception-p-1.png",
      "/portfolio/aly-benji-ceremony-p-1.png",
      "/portfolio/aly-benji-nightbefore-p-1.png",
      "/portfolio/aly-benji-reception.pdf",
      "/portfolio/aly-benji-ceremony.pdf",
      "/portfolio/aly-benji-nightbefore.pdf",
    ],
  },
  {
    id: 3,
    title: "SOZA Brand Identity & Landing Page",
    context: "School",
    category: "Branding Projects",
    company: "Class Project",
    date: "2024-03-01",
    thumbnail: "/portfolio/soza-thumb.png",
    description: "Brand identity and landing page for SOZA, a sparkling beverage concept. Went dark and moody with the palette to give it a premium feel — 'Happy Hour, Every Hour.' Built out the full system: colors, type, layout, and a landing page ready to hand off.",
    gallery: [
      "/portfolio/soza-thumb.png",
      "/portfolio/soza-landing.png",
      "/portfolio/soza-presentation.pdf",
      "/portfolio/soza-guidelines.pdf",
    ],
  },
  {
    id: 1,
    title: "Maverik Social Media Campaign",
    context: "Job",
    category: "Social Media",
    company: "Maverik",
    date: "2023-11-01",
    thumbnail: "/portfolio/maverik-cover.jpg",
    description: "Made 10+ Instagram posts a week for Maverik during my internship. Leaned into Gen Z trends and Maverik's adventure identity — one post hit 60k views, up from an average of 600. Also helped launch two sponsored campaigns with Red Bull and Ferrara.",
    gallery: [
      "/portfolio/maverik-cover.jpg",
      "/portfolio/maverik-video-1.mov",
      "/portfolio/maverik-video-2.mov",
      "/portfolio/maverik-post-4.png",
      "/portfolio/maverik-post-6.png",
      "/portfolio/maverik-girl-math.png",
      "/portfolio/maverik-love-language.png",
    ],
  },
  {
    id: 5,
    title: "Gerber Market Research",
    context: "School",
    category: "Branding Projects",
    company: "Class Project",
    date: "2023-06-01",
    thumbnail: "/portfolio/baby-food-thumb.png",
    description: "Market research project for Gerber done in school with my team. Dug into consumer behavior, the competitive landscape, and where there was room for Gerber to differentiate in the premium baby food space.",
    gallery: [
      "/portfolio/baby-food-thumb.png",
      "/portfolio/baby-food-report.pdf",
    ],
  },
  {
    id: 4,
    title: "H2GO Brand Identity",
    context: "School",
    category: "Branding Projects",
    company: "Class Project",
    date: "2023-09-01",
    thumbnail: "/portfolio/h2go-logo.jpg",
    description: "Logo and brand identity for H2GO, a hydration brand concept. Kept it simple — a water droplet worked into clean bold lettering. Also put together a short video ad to show the brand in motion.",
    gallery: [
      "/portfolio/h2go-logo.jpg",
      "/portfolio/h2go-video.mp4",
    ],
  },
  {
    id: 6,
    title: "BoomCloud Brand Strategy",
    context: "School",
    category: "Branding Projects",
    company: "Class Project",
    date: "2023-03-01",
    thumbnail: "/portfolio/boomcloud-thumb.png",
    description: "Brand strategy deck for BoomCloud, a music tech concept. Covered positioning, visual identity, audience personas, and go-to-market. Electric blue and hot pink — because it's a music brand.",
    gallery: [
      "/portfolio/boomcloud-thumb.png",
      "/portfolio/boomcloud-presentation.pdf",
    ],
  },
  {
    id: 7,
    title: "Marketing Association Events",
    context: "School",
    category: "Print & Digital",
    company: "BYU Marketing Advisory Center",
    date: "2024-02-22",
    thumbnail: "/portfolio/mktg-assoc-1.png",
    description: "Event graphics for the BYU Marketing Advisory Center. This one promoted the Winter 2024 Advisory Board Meeting — a two-day event with a service project and a panel discussion/bootcamp for marketing juniors and seniors.",
    gallery: [
      "/portfolio/mktg-assoc-1.png",
    ],
  },
  {
    id: 8,
    title: "Mignon Grad Announcements",
    context: "School",
    category: "Print & Digital",
    company: "Personal",
    date: "2024-05-01",
    thumbnail: "/portfolio/mignon-grad-1.png",
    description: "Made my own graduation announcement designs. Clean, simple, a little celebratory.",
    gallery: [
      "/portfolio/mignon-grad-1.png",
      "/portfolio/mignon-grad-2.png",
    ],
  },
  {
    id: 10,
    title: "Amy + Trey Wedding Invitations",
    context: "Personal",
    category: "Print & Digital",
    company: "Freelance",
    date: "2026-07-18",
    thumbnail: "/portfolio/amy-trey-2.png",
    description: "Wedding invite and save-the-date for Amy Ritz and Trey Richards — July 18, 2026 at Hatch Family Farm in Taylor, AZ. Western vibe, their engagement photo as the backdrop.",
    gallery: [
      "/portfolio/amy-trey-2.png",
      "/portfolio/amy-trey-invite.png",
    ],
  },
  {
    id: 11,
    title: "Mary's Baby Shower Designs",
    context: "Personal",
    category: "Print & Digital",
    company: "Freelance",
    date: "2025-04-21",
    thumbnail: "/portfolio/mary-shower-1.png",
    description: "Baby shower graphics for Mary. Soft colors, florals, the whole vibe — designed to work across digital invites and printed signage.",
    gallery: [
      "/portfolio/mary-shower-1.png",
      "/portfolio/mary-shower-2.png",
      "/portfolio/mary-shower-3.png",
    ],
  },
  {
    id: 12,
    title: "Alyson's Graduation Photos",
    context: "Personal",
    category: "Print & Digital",
    company: "Freelance",
    date: "2023-12-01",
    thumbnail: "/portfolio/alyson-grad-1.png",
    description: "Graduation photo graphics for Alyson. Laid her photos out with clean type so they were easy to share and felt put-together.",
    gallery: [
      "/portfolio/alyson-grad-1.png",
      "/portfolio/alyson-grad-2.png",
      "/portfolio/alyson-grad-3.png",
      "/portfolio/alyson-grad-4.png",
      "/portfolio/alyson-grad-5.png",
      "/portfolio/alyson-grad-6.png",
    ],
  },
];

export const EXPERIENCES = [
  {
    id: 1,
    role: "Implementation Specialist",
    company: "Alleva",
    period: "July 2025 – Present",
    description: "Onboard a new client each week onto customized behavioral health software, consulting on workflows and configuring systems to match each facility's needs. Recognized by a client for leading the \"best tech implementation they've ever seen\". Build comprehensive facility reports using Looker to enable data-driven decision-making.",
    filterCompany: "Alleva",
  },
  {
    id: 2,
    role: "Placement & Teaching Assistant",
    company: "BYU Marketing Advisory Center",
    period: "Jan 2024 – Apr 2025",
    description: "Taught 20+ university lectures covering career planning and strategy. Collaborated on 14 weeks of educational content including videos, presentations, and worksheets. Facilitated career placement for 350+ marketing students through strategic guidance and industry connections.",
    filterCompany: "BYU Marketing Advisory Center",
  },
  {
    id: 3,
    role: "Research Assistant",
    company: "BYU Marketing & Global Supply Chain",
    period: "Jan 2024 – Apr 2025",
    description: "Collaborated with Expert Voice to research online consumer trust (publication pending). Conducted literature analysis and developed a conjoint study on Qualtrics to gather consumer insights on online expertise.",
    filterCompany: "BYU Marketing Advisory Center",
  },
  {
    id: 4,
    role: "Business Analytics Intern",
    company: "Circle K",
    period: "May 2024 – Jun 2025",
    description: "Built 10+ Power BI reports supporting stakeholder needs and promotion insights. Identified $2M in sales misattribution by refining backend logic for Corporate vs. Franchise reporting. Created Power BI training videos to streamline onboarding and added currency conversion for CAD/USD stakeholder access.",
    filterCompany: "Circle K",
  },
  {
    id: 5,
    role: "Marketing & Social Media Intern",
    company: "Maverik",
    period: "Aug – Dec 2023",
    description: "Facilitated the launch of 2 marketing campaigns with sponsors including Red Bull and Ferrara. Boosted Instagram engagement 100x — from an average of 600 views to up to 60,000. Curated 10+ social posts and captions weekly inspired by current consumer trends.",
    filterCompany: "Maverik",
  },
  {
    id: 6,
    role: "Strategic Planning Team Lead",
    company: "Gabb Wireless",
    period: "Jan – Apr 2023",
    description: "Led a team of 5 in preparing and presenting research findings to company stakeholders. Generated a creative launch campaign for a kids' music streaming service and prepared influencer marketing strategies to reach 50,000+ individuals.",
    filterCompany: "Gabb",
  },
];

export const CATEGORIES = ["Social Media", "Branding Projects", "Print & Digital"];
export const CONTEXTS = ["Job", "School", "Personal"];
